kind: Job
apiVersion: batch/v1
metadata:
  name: parallel-job
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
        - name: parallel-pod
          image: kodekloud/random-error
      restartPolicy: Never