kind: Pod
apiVersion: v1
metadata:
  name: myapp-vol

spec:
  containers:
    - name: server
      image: nginx
      volumeMounts:
        - name: hostpath
          mountPath: "/usr/share/nginx/html"
      ports:
        - containerPort: 80
  
  volumes:
    - name: hostpath
      hostPath: 
        path: "/mnt"