apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: pod
    image: centos
    command: ["/bin/sh","-c","shuf -i 0-100 -n 1 >> /opt/radom.in"]
    volumeMounts:
    - name: my-volume
      mountPath: "/opt"  
    
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: myclaim
