kind: Pod
apiVersion: v1
metadata: 
  name: myapp-vol
spec:
  containers:
    - name: webserver-pod
      image: nginx
      #command: ["/bin/sh","-c","shuf -i 0-100 -n 1 >> /usr/share/nginx/html/random.out"]
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: webpage-vol

  volumes:
    - name: webpage-vol
      hostPath:
        path: /opt/webpage
        type: Directory