kind: Pod
apiVersion: v1
metadata:
  name: app-secret
spec:
  containers: 
    - name: app
      image: centos
      command: ["ping","localhost"]
      envFrom:
        - secretRef:
            name: secret-config
