kind: Pod
apiVersion: v1
metadata:
  name: app-secret
spec:
  containers: 
    - name: app
      image: centos
      command: ["ping","localhost"]
      volumeMounts:
        - name: app-secret-vol
          mountPath: /opt 
  volumes:
    - name: app-secret-vol
      secret:
        secretName: secret-config
